### ISSUE TITLE
[ERROR] Error initializing Cordova: Invalid Action

### ISSUE THREAD

**Issue by yurik94** [danielehrhardt/cordova-plugin-extended-device-information#1]
I get this error on Android Device building with Ionic 3.7.1:

[ERROR] Error initializing Cordova: Invalid Action

**Comment by yurik94** [comment]
`boolean wasValidAction = plugin.execute(action, rawArgs, callbackContext);`

action = getExtendedDeviceInfo

@ PluginManager.java (Cordova core)

**Comment by danielehrhardt** [comment]
Did you get this Error Message when you open the App or when you building the App?

**Comment by danielehrhardt** [comment]
How do you use the App in your Code?

**Comment by yurik94** [comment]
I got the error while cordova was initializing, on startup.
I used the ionic native wrapper as documented

Il 21 ott 2017 18:00, "Daniel Ehrhardt" <notifications@github.com> ha
scritto:

**Comment by danielehrhardt** [comment]
Please install 2.1.4
ionic cordova plugin add cordova-plugin-extended-device-information@2.1.4

**Comment by danielehrhardt** [comment]
Problem should be fixed with #2.1.5. 
Thank you for create this Issue.
