### ISSUE TITLE
Ionic native interface not working with the plugin

### ISSUE THREAD

**Issue by AUK4GIT** [danielehrhardt/cordova-plugin-extended-device-information#6]
Hi Daniel,
This plugin seems to be wrapped in ionic native plugin https://ionicframework.com/docs/native/extended-device-information/

But the variables are always returned null when accessed using the ionic native interface.
"The Memory is: null"

Can you please look into this.

Following is my system config
Ionic:

   ionic (Ionic CLI)  : 4.0.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.5

Thanks

**Comment by danielehrhardt** [comment]
Wait until this is merged https://github.com/ionic-team/ionic-native/pull/2641
