### ISSUE TITLE
issue when cordova-plugin-device is used along with this plugin

### ISSUE THREAD

**Issue by AUK4GIT** [danielehrhardt/cordova-plugin-extended-device-information#7]
Hi Daniel,

I have been working to make use of this plugin in my app without any issues for quite a long time. One new observation I found is that this plugin doesnot work as required when cordova-plugin-device is also installed in the same app.
Upon investigation, I found out that the event name used for cordova channel "onCordovaInfoReady" is same in both the plugins due to which only one of the event is registered. Can you change the name to something else and fix it. I have also included the fix for iOS in the below code.

```
channel.createSticky('onCordovaInformationReady');
channel.waitForInitialization('onCordovaInformationReady');
channel.onCordovaReady.subscribe(function () {
        if(cordova.platformId === 'android') {
            self.getRAMSize(function(info){
                self.memory = info.memory || 'unknown';
                self.cpumhz = info.cpumhz || 'unknown';
                self.totalstorage = info.totalstorage || 'unknown';
                channel.onCordovaInformationReady.fire();
            }, function(e){
                utils.alert('[ERROR] Error initializing Cordova: ' + e);
            });
        } else {
            channel.onCordovaInformationReady.fire();
        }
    });
```

Can you also fix the ionic native plugin issue.
Thanks
Uday Kiran

**Comment by danielehrhardt** [comment]
Could you please check it?
